apiVersion: batch/v1
kind: Job
metadata:
  name: engine-performance-process-from-begin
  namespace: default
spec:
  template:
    metadata:
      name: engine-performance-process-from-begin
      labels:
        app: engine-performance-process-from-begin
    spec:
      containers:
      - name: engine-performance-process-from-begin
        image: docker.io/assafsh2/engineperformanceprocess
        env:
        - name: KAFKA_ADDRESS
          value: kafka.kafka:9092
        - name: SCHEMA_REGISTRY_ADDRESS
          value: http://schema-registry.kafka:8081
        - name: SCHEMA_REGISTRY_IDENTITY
          value: "2010"
        - name: PRINT_TO_FILE
          value: "false"
        - name: SEC_TO_DELAY
          value: "0"
        - name: SOURCE_NAME
          value: "source4"
        - name: JAVA_OPTIONS
          value: "-Xmx1024m"
        - name: START_FROM_BEGINNING
          value: "true"
        - name: MULTI_MESSAGES
          value: "false"
        - name: NUM_OF_CYCLES
          value: "3"
        - name: NUM_OF_UPDATES
          value: "3"
      restartPolicy: Never
