kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: performance-process-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: engine-performance-process
      type: output
