apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stream-dynamic1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: stream-dynamic1
      labels:
        app: stream-dynamic1
    spec:
      containers:
      - name: stream
        image: assafsh2/interfaceconverter:latest
        env:
        - name: KAFKA_ADDRESS
          value: kafka.kafka:9092
        - name: SCHEMA_REGISTRY_IP
          value: http://schema-registry.kafka:8081
        - name: SCHEMA_REGISTRY_ADDRESS
          value: http://schema-registry.kafka:8081
        - name: SCHEMA_REGISTRY_IDENTITY
          value: "2010"
        - name: DEBUG_LEVEL
          value: ERROR
        - name: INTERFACE_NAME
          value: source1
        - name: SOURCE_NAME
          value: source1

